@Library('pipeline-library')_

VitisLibPipeline (branch: 'next', libname: 'xf_compression', run_sw_in_pr: 'true',
TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu',
upstream_dependencies: 'xf_security,next,../security', devtest: 'RunDeploy.sh', TOOLVERSION: '2024.1_stable_latest', 'os_types' : 'centos7:rhel7')
