@Library('pipeline-library')_

VitisLibPipeline (branch: 'next', libname: 'xf_opencv', TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu',
                  devtest: 'RunDeploy.sh', TOOLVERSION: '2023.1_stable_latest')
