@Library('pipeline-library')_

VitisLibPipeline (branch: 'main', libname: 'xf_opencv', TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu',
                  devtest: 'RunDeploy.sh', TOOLVERSION: '2022.2_released')
