@Library('pipeline-library')_

VitisLibPipeline (branch: 'next', 
                  libname: 'xf_ultrasound',
                  TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu:vitis_hw_build:vitis_hw_run:vitis_aie_sim:vitis_aie_x86sim',
                  upstream_dependencies: '',
                  devtest: 'RunDeploy.sh', 
                  TOOLVERSION: '2024.1_stable_latest')