PARALLEL_BLOCK  := 1 
MULTIPLE_BYTES  := 8
ENABLE_P2P := 1

ifneq ($(findstring u2x4, $(DEVICE)), u2x4)
	ENABLE_P2P := 0
endif

CXXFLAGS += -DPARALLEL_BLOCK=$(PARALLEL_BLOCK) -DENABLE_P2P=$(ENABLE_P2P)
