C_COMPUTE_UNITS := 2
H_COMPUTE_UNITS := 2
D_COMPUTE_UNITS := 9 
PARALLEL_BLOCK  := 8
MULTIPLE_BYTES  := 8
VERBOSE := no

CXXFLAGS += -DPARALLEL_BLOCK=$(PARALLEL_BLOCK) -DC_COMPUTE_UNIT=$(C_COMPUTE_UNITS) \
            -DT_COMPUTE_UNIT=$(T_COMPUTE_UNITS) -DH_COMPUTE_UNIT=$(H_COMPUTE_UNITS) \
            -DD_COMPUTE_UNIT=$(D_COMPUTE_UNITS) -DOVERLAP_HOST_DEVICE

# Generate Verbose content
ifeq ($(VERBOSE),yes)
CXXFLAGS += -DVERBOSE
endif

