@Library('pipeline-library')_
VitisLibPipeline ( libname:'xf_dsp',
                   upstream_dependencies:'xf_utils_hw,next,../utils; xf_data_mover,next,../data_mover; dsplib_internal_scripts,main,../dsplib_internal_scripts')
