@Library('pipeline-library')_
VitisLibPipeline (branch: 'master', libname: 'xf_graph', TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu:vitis_hw_build',
                  upstream_dependencies: 'xf_utils_hw,master,../utils; xf_database,master,../database; xf_fintech,master,../quantitative_finance',
		  email: 'shengl@xilinx.com', devtest: 'RunDeploy.sh', TOOLVERSION: '2021.2_released')
