#define TYPE_FLOW_WIDTH 16
#define TYPE_FLOW_INT 10
#define TYPE_FLOW_TYPE ap_fixed<TYPE_FLOW_WIDTH, TYPE_FLOW_INT>

#define INPUT_PTR_WIDTH 32
#define OUTPUT_PTR_WIDTH 32

#define WINSIZE_OFLOW 11

#define NUM_LEVELS 5
#define NUM_ITERATIONS 5

#define HEIGHT 1080
#define WIDTH 1920

#define NUM_LINES_FINDIT 50

// harris parameters
#define FILTER_WIDTH 3
#define BLOCK_WIDTH 3
#define NMS_RADIUS 1
#define MAXCORNERS 10000