@Library('pipeline-library')_
VitisLibPipeline (branch: 'main', libname: 'xf_security', TARGETS: 'hls_csim:hls_cosim:vivado_syn:vitis_sw_emu:vitis_hw_emu:vitis_hw_build',
                  upstream_dependencies: 'xf_utils_hw,main,../utils',
                  devtest: 'RunDeploy.sh', TOOLVERSION: '2022.1_released', mail_on:'daily:PR')
