@Library('pipeline-library')_
VitisLibPipeline (branch: 'next', libname: 'xf_security', TARGETS: 'hls_csim:hls_cosim:vivado_syn:vitis_sw_emu:vitis_hw_emu:vitis_hw_build',
                  upstream_dependencies: 'xf_utils_hw,next,../utils',
                  devtest: 'RunDeploy.sh', TOOLVERSION: '2024.1_stable_latest', mail_on:'daily:PR')
