#!/bin/bash
# vim: set filetype=sh :

#
# Copyright (C) 2019-2022, Xilinx, Inc.
# Copyright (C) 2022-2023, Advanced Micro Devices, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e
script_path=$(readlink -f $(dirname $0))
if [ "x$1" = "x--tool-dir" ]; then
  shift
  tool_dir=$1
  shift
else
  tool_dir=${script_path}
fi

# Use python3 shipped with Vitis
export PATH=${XILINX_VITIS}/tps/lnx64/python-3.8.3/bin:$PATH
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}${LD_LIBRARY_PATH:+:}${XILINX_VITIS}/tps/lnx64/python-3.8.3/lib:${XILINX_VIVADO}/tps/lnx64/gcc-6.2.0/lib64

if ! hash python3 &> /dev/null; then
  echo "[ERROR] python3 is not found in PATH, and XILINX_VITIS is not set either. Abort!"
  false
fi

if [ ! -f ${tool_dir}/py3env/.ok -o ! -f ${tool_dir}/dataConverter ]; then
  make -C ${script_path} DEST_DIR=${tool_dir}
fi

source ${tool_dir}/py3env/bin/activate
${script_path}/internal/generate_kernels.py --tool-dir ${tool_dir} "$@"
