@Library('pipeline-library')_
VitisLibPipeline (branch: 'main', libname: 'xf_DataAnalytics', TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu:vitis_hw_build',
                  upstream_dependencies: 'xf_utils_hw,main,../utils; xf_compression,main,../data_compression; xf_security,main,../security; xf_graph,main,../graph; xf_database,main,../database',
                  devtest: 'RunDeploy.sh', TOOLVERSION: '2022.1_released')
