@Library('pipeline-library')_
VitisLibPipeline (branch: 'main', libname: 'xf_utils_hw', TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu:vitis_hw_build',
                  devtest: 'RunDeploy.sh', TOOLVERSION: '2022.1_released', mail_on:'daily:PR')
