@Library('pipeline-library')_
VitisLibPipeline (branch: 'main', libname: 'xf_motorcontrol', TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu:vitis_hw_build',
                  upstream_dependencies: '',
		  		  devtest: 'RunDeploy.sh', TOOLVERSION: '2023.1_released', 'os_types' : 'centos7:rhel7')
