PART   =  xcvc1902-vsva2197-2MP-e-S
VSSCFG =  vss_connectivity.cfg
XO     =  ../_x_temp.hw.xilinx_vck190_base_202420_1/vck190_test_harness.xo 
LIBADF =  ../_x_temp.hw.xilinx_vck190_base_202420_1/libadf.a


vss:
	v++ --link --mode vss --part ${PART}  --config ${VSSCFG} ${LIBADF} ${XO}
