@Library('pipeline-library')_
VitisLibPipeline ( libname:'xf_codec',
                   upstream_dependencies:'xf_utils_hw,next,../utils; xf_database,next,../database; xf_fintech,next,../quantitative_finance')