@Library('pipeline-library')_
VitisLibPipeline (branch: 'main', libname: 'xf_fintech', TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu:vitis_hw_build',
                  upstream_dependencies: 'xf_utils_hw,main,../utils; xf_solver,main,../solver',
                  devtest: 'RunDeploy.sh', TOOLVERSION: '2022.1_released')
