@Library('pipeline-library')_
VitisLibPipeline (branch: 'next', libname: 'xf_fintech', TARGETS: 'hls_csim:hls_csynth:hls_cosim:vitis_sw_emu:vitis_hw_emu:vitis_hw_build',
                  upstream_dependencies: 'xf_utils_hw,next,../utils; xf_solver,next,../solver',
                  devtest: 'RunDeploy.sh', TOOLVERSION: '2023.2_stable_latest')
