C_COMPUTE_UNITS := 1
D_COMPUTE_UNITS := 1
PARALLEL_BLOCK  := 8
SINGLE_XCLBIN   := false

CXXFLAGS += -DPARALLEL_BLOCK=$(PARALLEL_BLOCK) -DC_COMPUTE_UNIT=$(C_COMPUTE_UNITS) -DD_COMPUTE_UNIT=$(D_COMPUTE_UNITS) -DSINGLE_XCLBIN=$(SINGLE_XCLBIN) -DOVERLAP_HOST_DEVICE
